[package]
name = "MultiPlatform_screenCasting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.9.0", features = ["tokio", "image", "svg"] }
iced_aw = { version = "0.7.0", features = ["tabs"] }
tokio =  {version = "1.15", features = ["full"] }
scrap = "0.5.0"
scap = {git="https://github.com/giuseppe2028/scap.git"}
nix = { version = "0.29.0", features = ["signal"] }