workspace = { members = [ "ffmpeg","network", "screenshare"] }
[package]
name = "MultiPlatform_screenCasting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.6.3"
minifb = "0.27.0"
scrap = "0.5.0"
