[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.40.0",features = ["full"]}
scap = "0.0.5"
minifb = "0.27.0"
image = "0.24.9"